CREATE TABLE IF NOT EXISTS 原始_交通事故_原因及傷亡 (
    年月 VARCHAR(255),
    分局 VARCHAR(255),
    駕駛人過失_超速失控_含未減速 INT,
    駕駛人過失_酒後駕車 INT,
    駕駛人過失_未注意車前狀況 INT,
    駕駛人過失_肇事逃逸 INT,
    駕駛人過失_未保持行車安全間距 INT,
    駕駛人過失_未依規定讓車 INT,
    駕駛人過失_行駛疏忽 INT,
    駕駛人過失_違反號誌管制 INT,
    駕駛人過失_違反標誌標線 INT,
    駕駛人過失_逆向行駛 INT,
    駕駛人過失_轉彎不當 INT,
    駕駛人過失_搶越行人穿越道 INT,
    駕駛人過失_其他 INT,
    機件故障 INT,
    行人過失 INT,
    交通管制設施缺陷 INT,
    其他 INT,
    PRIMARY KEY (年月, 分局)
);